export const DEFAULT_PLAQUE_TITLE = "Donald J. Trump"
// "For staggering leadership"
// "He Does His Duty"
// "Behind every great man is fake news"
// "He can read a crowd like a book...\n...if he could read a book"
export const DEFAULT_PLAQUE_SUBTITLE = "He does his duty,\nOnto the American people"
